### ISSUE TITLE
Implement using the 'install' program for make install

### ISSUE THREAD

**Issue by aremmell** [aremmell/libsir#4]
Do it.

**Comment by aremmell** [comment]
Optionally, switch to CMake/autotools.

**Comment by johnsonjh** [comment]
noooooo cmake 👎🏻  Of course just preference. :)

The "problem" with install is that install itself is very non-standard.  The System V ones that AIX and Solaris use aren't compatible with the Linux ones *nor* the BSD ones.  Some BSD baseline behavior is standard.

In case you are interested I did a survey of all the install programs and I put together an amalgamation based mostly on the OpenBSD one, which is included in my OpenVi distribution.  I haven't yet switched over to using it, but it works and if you want to steal it go ahead.  It could easily be made one file and avoid the compat headers.  I use them simply because I have them.

It's at https://github.com/johnsonjh/OpenVi/tree/master/xinstall

**Comment by aremmell** [comment]
In what way are they not compatible? I mean, at least they know the right directories to stick library files and headers, right? That's a step up from my hacky hand-rolled Makefile recipe.

**Comment by johnsonjh** [comment]
The options between them aren't remotely compatible and there is no standard, and very few common options:

AIX: https://www.ibm.com/docs/en/aix/7.3?topic=i-install-command
FreeBSD: https://man.freebsd.org/cgi/man.cgi?query=install&apropos=0&sektion=0&manpath=FreeBSD+14.0-CURRENT&arch=default&format=html
Solaris: https://docs.oracle.com/cd/E88353_01/html/E37839/install-1.html

Making things worse instead of better, AIX has a installbsd command too, which is closer to BSD.  Other OS's have "bsdinstall".  Some have three or four install programs (install, xinstall, bsdinstall, etc.) that all work differently.

When you use GNU autoconf, autoconf bundles its own version install(1) and doesn't use the system ones.  That one is written in a restricted POSIX shell dialect so it should run everywhere.  It's at https://git.savannah.gnu.org/cgit/autoconf.git/tree/build-aux/install-sh

I made the C one above to solve the same problem for OpenVi but I haven't gotten around to using it yet.

**Comment by aremmell** [comment]
You know, none of this would be a problem if everyone who branched off of Unix didn't change things just for the sake of changing them. Or maybe spoke to the other people tinkering with the same ideas... hindsight: 20/20
