### ISSUE TITLE
Update platform/architecture/toolset support matrix

### ISSUE THREAD

**Issue by aremmell** [aremmell/libsir#67]
We need to create a CSV or spreadsheet of known supported OSes, architectures, and toolsets.

This will be source material that we can keep around in the docs folder, and use it to update the markdown/html.

**Comment by johnsonjh** [comment]
@aremmell 

Something like this?  This is actually, so far. what I've really tested (sorry, already it GitHub-ified Markdown): 

| System | Toolchain | 
| -:|:- |
| **Linux**&nbsp;2.6.32+<br>(glibc&nbsp;2.18+, musl&nbsp;1.2.3+, uClibc‑ng&nbsp;1.0.43+, Bionic&nbsp;19+) | **GCC** (4.8.4 - 13.1.1),&nbsp; **Clang** (6 - 16.0.6),&nbsp; **Oracle Studio C/C++** (12.6),&nbsp; **IBM Advance Toolchain** (14 - 16),&nbsp; **IBM Open XL C/C++** (17.1.1),&nbsp; **NVIDIA HPC SDK C/C++** (23.5),&nbsp; **Arm HPC C/C++** (22.1),&nbsp; **AMD Optimizing C/C++** (4.0.0),&nbsp; **Intel oneAPI DPC++/C++** (2023.1),&nbsp; **Intel C++ Compiler Classic** (2021.9),&nbsp; **Android NDK** (r25c) |
| **NetBSD**&nbsp;9.2+ | **GCC** (7.5 - 13.1),&nbsp; **Clang** (15.0.7) |
| **FreeBSD**&nbsp;11.4+ | **GCC** (11.4 - 12.2),&nbsp; **Clang** (10.0.0 - 14.0.5) |
| **DragonFly**&nbsp;**BSD**&nbsp;6.4+ | **GCC** (8.3 - 13),&nbsp; **Clang** (10.0.1 - 14.0.6) |
| **Haiku**&nbsp;R1b4 | **GCC** (11.2),&nbsp; **Clang** (12.0.1) |
| **Solaris**&nbsp;11.4 | **GCC** (10.3 - 11.2),&nbsp; **Clang** (6 - 11),&nbsp; **Oracle Studio C/C++** (12.6) |
| **illumos** | **GCC** (7.5 - 11.3),&nbsp; **Clang** (15.0.7) |
| **Windows**&nbsp;10+ | **Microsoft Visual C/C++** (17.6),&nbsp; **GCC-MinGW** (12.2.1 - 13.1.1),&nbsp; **LLVM-MinGW** (15.0 - 16.0.6) |
| **Cygwin**&nbsp;3.4+ | **GCC** (11.2 - 11.4) |
| **macOS**&nbsp;10.15+ | **Xcode** (12.4 - 15),&nbsp; **GCC** (10.4 - 13.1),&nbsp; **Clang** (12.0.1 - 16.0.6) |
| *Coming soon* | *Support planned for* **AIX** *and* **OpenBSD** |

I don't think it makes sense to list every architecture in the table - so far, I've actually tested it on: x86_64, i686, ARM (ARMv6, ARMv7HF), ARM64, PowerPC, PPC64le, MIPS (74Kc), S390X, SuperH (SH-4A), RISC-V (RV64), OR1K (OR1200), and m68k (68040) for Linux, PPC64(BE) for Linux and AIX, etc.  Really, if it doesn't work on some architecture it's probably a bug!  We should say that these are tested versions, others may work, etc etc...  I'll let you word it.

**Comment by johnsonjh** [comment]
and in some cases, these are the minimum versions.  I know that Linux versions before 2.6.32 (like Linux 2.4) won't be able to work right due to thread stuff, and versions of NetBSD before 8 can never work due to missing C11 support, etc.  For musl libc I know v1.2.3 is the minimum (because it's the first to support pthread_getname_np and it doesn't give any version or test macros to gracefully degrade).  In other cases, I know Windows 7 will almost surely work with the MinGW compilers binaries, but I've not tested it.  I don't think we should get too in-depth, it shouldn't be a full-time job maintaining and updating the chart.  It should exist to impress people and let them know that this thing really is portable. :)
