### ISSUE TITLE
256-color and RGB color support

### ISSUE THREAD

**Issue by aremmell** [aremmell/libsir#93]
Implement

- [x] `\033[<fg=38|bg=48>;5;<0..255>m`
- [x] `\033[<fg=38|bg=48>;2;<R=0..255>;<G=0..255>;<B=0..255>m`
- [ ] Polish
- [ ] Testing
  - [x] Test changing modes
  - [x] Test `_sir_validtextstyle`
  - [ ] Should add to thread race test
  - [ ] Probably need a `sir_settextstylergb`
- [ ] Replace magic numbers with constants
- [ ] Documentation

**Comment by aremmell** [comment]
@johnsonjh you figure there are any terminals out there so old they don't support 256 colors? I'd like to just drop 16-color mode. 256 simplifies things a lot because the numeric value is the color.

**Comment by johnsonjh** [comment]
Lots, unfortunately.

At least AIX and older but still supported Solaris don't even come with termcap/terminfo entries for any *256color* terminals ...

**Comment by johnsonjh** [comment]
I've got:
```
if [ "${TERM:-}" = "xterm-256color"  ]; then TERM=xterm-color; fi
if [ "${TERM:-}" = "screen-256color" ]; then TERM=xterm-color; fi
if [ "${TERM:-}" = "tmux-256color"   ]; then TERM=xterm-color; fi
export TERM
```
in my .profile on most of those systems for just that reason, otherwise the terminal ends up a mess.

**Comment by aremmell** [comment]
You think it'd be sufficient to have libsir test for those values in $TERM and use 256 by default if it's set to any of those, or would it be preferable to default to 16-color mode, and require explicit elevation?

**Comment by aremmell** [comment]
Well, if it came down to it i could use `popen` and comm with `tput`. I'll look into it after I figure out how to totally undo this entire design around 16-colors and add these other modes

**Comment by johnsonjh** [comment]
Well, for true color support, the only realiable way is to talk to the terminal:

![IMG_7866](https://github.com/aremmell/libsir/assets/61629094/3266c98c-ceb8-40b8-b38a-8071728475f5)

If the terminfo database request for the colors capability returns anything less than "8", you shouldn't even try the above because it'll just print junk.  Conversely, you can test the "COLORTERM" environment variable for "truecolor" or "24bit" and which means it should be supported so it would be safe to at least test (regardless of the terminfo result.)

**Comment by johnsonjh** [comment]
I'd really need to think about the sanest way to do this because the capabilities can change at runtime as well, and they often do, like attaching and detaching tmux or other terminal multiplexers or using mosh that have a concept of a terminal shim and do "inner" and "outer" terminals or some kind translation.

Anyway, it's non-trivial.  But I can get definitive answers, just give me a couple days to prod the right people.

**Comment by johnsonjh** [comment]
Yes, I say default to only 8/16 color only.

Leave it up to the developer of the application using libsir to decide if and when to enable 256-color or TrueColor modes.

**Comment by aremmell** [comment]
This is a pretty huge pain to support runtime changing of the color mode. It'll involve another mutex lock.

Maybe it should be a compile-time setting.

**Comment by johnsonjh** [comment]
Problem there is, let's say I'm using the AIX machine.  If I SSH to a Linux machine from the LFT console ("low-functioning terminal"), I've got two colors I can see.  If I use aixterm, I have 16 colors, and if I use the new (and not installed by default) xterm I'd have 256-color or TrueColor.  

The only way (I know of) for the application to show the right color codes would be to use terminfo (and/or COLORTERM) to query the actual terminal in use.  Let's say TrueColor mode is enabled at compile time, that would mean that you'd have to use a TrueColor terminal, even if connecting remotely, right? Since 256color or TrueColor escape codes wouldn't work, the only way to make a portable application would be to never compile the 256color or TrueColor support?

**Comment by aremmell** [comment]
arc4random + rgb = fun:

<img width="638" alt="Screenshot 2023-07-11 at 07 45 20" src="https://github.com/aremmell/libsir/assets/812759/6db81e3f-cb3c-4b7a-965a-da8de627847c">
